apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - config.yml=conf/config.yml
  name: docker-registry

namespace: docker-registry

resources:
- docker-registry-deployment.yaml
- docker-registry-namespace.yaml
- docker-registry-pvc.yaml
- docker-registry-route.yaml
- docker-registry-service.yaml

secretGenerator:
- files:
  - htpasswd=conf/htpasswd
  name: docker-registry-htpasswd
